language: c++
os: linux
dist: trusty
sudo: false

notifications:
  email:
    recipients: sghosh23@ncsu.edu
    on_success: change
    on_failure: always

addons:	
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - python3

script:
- cd hello_world; g++ hello_world.cpp; python test.py
